name: Check compilation

on:
  push:
    branches:
      - master


jobs:
  lib-socket:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run make
        run: make -C libs/socket

  client:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    needs: lib-socket
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run make
        run: make client

  server:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker:devel
    needs: lib-socket
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run
    - name: Run make
      run: make server