name: Check compilation

on:
  push:
    branches:
      - master


jobs:
  client:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run make
        run: make client

  server:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Run
    - name: Run make
      run: make server