name: Run tests

on:
  workflow_run:
    workflows: ["Check compilation"]
    branches:
      - master
    types:
      - completed


jobs:
  tests:
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run tests
        run: make tests_run

      - name: Show coverage
        run: make coverage